# Generated by Django 5.1.7 on 2025-04-07 14:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penyelia',
            options={'ordering': ['-created_at'], 'verbose_name': 'penyelia', 'verbose_name_plural': 'penyelia'},
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='prodi',
            field=models.CharField(choices=[('Ilmu Komputer', 'Ilmu Komputer'), ('Sistem Informasi', 'Sistem Informasi')], default='Ilmu Komputer', max_length=20),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='invitation_token',
            field=models.CharField(blank=True, help_text='Token for one-time password setup link.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pendaftarankp',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendaftaranmbkm',
            name='feedback_penolakan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pendaftaranmbkm',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='semester',
            name='gasal_genap',
            field=models.CharField(choices=[('Gasal', 'Gasal'), ('Genap', 'Genap')], max_length=5),
        ),
        migrations.CreateModel(
            name='LaporanKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_laporan', models.FileField(upload_to='laporan/')),
                ('status_persetujuan_penyelia', models.CharField(choices=[('-', '-'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='-', max_length=50)),
                ('feedback_penolakan_penyelia', models.TextField(blank=True, null=True)),
                ('feedback_dosen', models.TextField(blank=True, null=True)),
                ('history', models.JSONField(default=dict)),
                ('file_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('Belum Dinilai', 'Belum Dinilai'), ('Perlu Revisi', 'Perlu Revisi'), ('Sudah Dinilai Namun Belum Sesuai Format', 'Sudah Dinilai Namun Belum Sesuai Format'), ('Sudah Bisa Diberikan ke Perpustakaan', 'Sudah Bisa Diberikan ke Perpustakaan')], default='Belum Dinilai', max_length=50)),
                ('nilai_abstrak', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai_isi', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai_lampiran', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai_konsistensi', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai_kerapihan', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai', models.FloatField(blank=True, null=True)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.pendaftarankp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaporanMBKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_laporan', models.FileField(upload_to='laporan/')),
                ('status_persetujuan_penyelia', models.CharField(choices=[('-', '-'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='-', max_length=50)),
                ('feedback_penolakan_penyelia', models.TextField(blank=True, null=True)),
                ('feedback_dosen', models.TextField(blank=True, null=True)),
                ('history', models.JSONField(default=dict)),
                ('file_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('Belum Dicek', 'Belum Dicek'), ('Perlu Revisi', 'Perlu Revisi'), ('Disetujui', 'Disetujui')], default='Belum Dicek', max_length=50)),
                ('sks_klaim', models.IntegerField()),
                ('status_persetujuan_dosen', models.CharField(choices=[('-', '-'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='-', max_length=50)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.pendaftaranmbkm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogMingguan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status_persetujuan', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('alasan_penolakan', models.TextField(blank=True, null=True)),
                ('total_jam', models.FloatField(default=0.0)),
                ('pendaftaran_kp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.pendaftarankp')),
                ('pendaftaran_mbkm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.pendaftaranmbkm')),
            ],
        ),
        migrations.CreateModel(
            name='AktivitasHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('deskripsi', models.TextField()),
                ('log_mingguan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_harian', to='testapp.logmingguan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='logmingguan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pendaftaran_kp__isnull', False), ('pendaftaran_mbkm__isnull', True)), models.Q(('pendaftaran_kp__isnull', True), ('pendaftaran_mbkm__isnull', False)), _connector='OR'), name='hanya_satu_pendaftaran'),
        ),
    ]
