# Generated by Django 5.1.7 on 2025-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_penyelia_options_mahasiswa_prodi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyelia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
