# Generated by Django 5.1.7 on 2025-04-21 08:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_penyelia_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManajemenFakultas',
            new_name='Manajemen',
        ),
        migrations.DeleteModel(
            name='Kaprodi',
        ),
    ]
