# Generated by Django 5.1.6 on 2025-03-03 04:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penyelia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('perusahaan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramMBKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('minimum_sks', models.IntegerField()),
                ('maksimum_sks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=16, unique=True)),
                ('aktif', models.BooleanField(default=False)),
                ('gasal_genap', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PendaftaranMBKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_semester', models.IntegerField()),
                ('sks_diambil', models.IntegerField()),
                ('request_status_merdeka', models.BooleanField(default=False)),
                ('rencana_lulus_semester_ini', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=255)),
                ('estimasi_sks_konversi', models.IntegerField()),
                ('persetujuan_pa', models.FileField(blank=True, null=True, upload_to='persetujuan_pa/')),
                ('tanggal_persetujuan', models.DateField(blank=True, null=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('pernyataan_komitmen', models.BooleanField(default=False)),
                ('status_pendaftaran', models.CharField(max_length=50)),
                ('history', models.JSONField(default=list)),
                ('file_timestamp', models.DateTimeField(blank=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PendaftaranMahasiswa.mahasiswa')),
                ('penyelia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PendaftaranMahasiswa.penyelia')),
                ('program_mbkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PendaftaranMahasiswa.programmbkm')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PendaftaranMahasiswa.semester')),
            ],
        ),
        migrations.CreateModel(
            name='PendaftaranKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_semester', models.IntegerField()),
                ('sks_diambil', models.IntegerField()),
                ('sks_lulus', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
                ('total_jam_kerja', models.IntegerField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('pernyataan_komitmen', models.BooleanField(default=False)),
                ('status_pendaftaran', models.CharField(max_length=50)),
                ('history', models.JSONField(default=list)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PendaftaranMahasiswa.mahasiswa')),
                ('penyelia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PendaftaranMahasiswa.penyelia')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PendaftaranMahasiswa.semester')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PembimbingAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManajemenFakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Kaprodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
