# Generated by Django 5.1.7 on 2025-03-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMingguan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.PositiveIntegerField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('disetujui_penyelia', models.BooleanField(blank=True, null=True)),
                ('catatan_penyelia', models.TextField(blank=True, null=True)),
                ('program_kp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.pendaftarankp')),
                ('program_mbkm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.pendaftaranmbkm')),
            ],
            options={
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='AktivitasHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('deskripsi', models.TextField()),
                ('log_mingguan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_harian', to='database.logmingguan')),
            ],
        ),
    ]
