# Generated by Django 5.1.7 on 2025-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_logmingguan_aktivitasharian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logmingguan',
            options={},
        ),
        migrations.RenameField(
            model_name='logmingguan',
            old_name='program_kp',
            new_name='pendaftaran_kp',
        ),
        migrations.RenameField(
            model_name='logmingguan',
            old_name='program_mbkm',
            new_name='pendaftaran_mbkm',
        ),
        migrations.RemoveField(
            model_name='logmingguan',
            name='disetujui_penyelia',
        ),
        migrations.RemoveField(
            model_name='logmingguan',
            name='minggu_ke',
        ),
        migrations.AddField(
            model_name='logmingguan',
            name='status_persetujuan',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='logmingguan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pendaftaran_kp__isnull', False), ('pendaftaran_mbkm__isnull', True)), models.Q(('pendaftaran_kp__isnull', True), ('pendaftaran_mbkm__isnull', False)), _connector='OR'), name='hanya_satu_pendaftaran'),
        ),
    ]
