# Generated by Django 5.1.7 on 2025-04-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_logmingguan_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmingguan',
            old_name='catatan_penyelia',
            new_name='alasan_penolakan',
        ),
        migrations.AddField(
            model_name='logmingguan',
            name='total_jam',
            field=models.IntegerField(default=0),
        ),
    ]
