# Generated by Django 5.1.7 on 2025-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_catatan_penyelia_logmingguan_alasan_penolakan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmingguan',
            name='total_jam',
            field=models.FloatField(default=0.0),
        ),
    ]
