# Generated by Django 5.1.7 on 2025-04-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_logmingguan_total_jam'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='prodi',
            field=models.CharField(choices=[('Ilmu Komputer', 'Ilmu Komputer'), ('Sistem Informasi', 'Sistem Informasi')], default='Ilmu Komputer', max_length=20),
        ),
    ]
