# Generated by Django 5.1.7 on 2025-04-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_penyelia_options_penyelia_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('log_mingguan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari', to='database.logmingguan')),
            ],
            options={
                'ordering': ['tanggal'],
                'unique_together': {('log_mingguan', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('deskripsi', models.TextField()),
                ('hari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to='database.hari')),
            ],
        ),
        migrations.DeleteModel(
            name='AktivitasHarian',
        ),
    ]
