# Generated by Django 5.1.7 on 2025-04-20 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_hari_aktivitas_delete_aktivitasharian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hari',
            name='log_mingguan',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hari', to='database.logmingguan'),
        ),
    ]
