# Generated by Django 5.1.7 on 2025-04-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_hari_log_mingguan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktivitas',
            options={'ordering': ['jam_mulai']},
        ),
    ]
