# Generated by Django 5.1.7 on 2025-04-06 04:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_detil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penyelia',
            options={'ordering': ['-created_at'], 'verbose_name': 'penyelia', 'verbose_name_plural': 'penyelia'},
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='prodi',
            field=models.CharField(choices=[('Ilmu Komputer', 'Ilmu Komputer'), ('Sistem Informasi', 'Sistem Informasi')], default='Ilmu Komputer', max_length=20),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penyelia',
            name='invitation_token',
            field=models.CharField(blank=True, help_text='Token for one-time password setup link.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pendaftarankp',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendaftaranmbkm',
            name='feedback_penolakan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pendaftaranmbkm',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='semester',
            name='gasal_genap',
            field=models.CharField(choices=[('Gasal', 'Gasal'), ('Genap', 'Genap')], max_length=5),
        ),
        migrations.CreateModel(
            name='LaporanKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_laporan', models.FileField(upload_to='laporan/')),
                ('status_persetujuan_penyelia', models.CharField(choices=[('-', '-'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='-', max_length=50)),
                ('feedback_penolakan_penyelia', models.TextField(blank=True, null=True)),
                ('feedback_dosen', models.TextField(blank=True, null=True)),
                ('history', models.JSONField(default=dict)),
                ('file_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('Belum Dinilai', 'Belum Dinilai'), ('Perlu Revisi', 'Perlu Revisi'), ('Sudah Dinilai Namun Belum Sesuai Format', 'Sudah Dinilai Namun Belum Sesuai Format'), ('Sudah Bisa Diberikan ke Perpustakaan', 'Sudah Bisa Diberikan ke Perpustakaan')], default='Belum Dinilai', max_length=50)),
                ('nilai_abstrak', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai_isi', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai_lampiran', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai_konsistensi', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai_kerapihan', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nilai', models.FloatField(blank=True, null=True)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_detil.pendaftarankp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaporanMBKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_laporan', models.FileField(upload_to='laporan/')),
                ('status_persetujuan_penyelia', models.CharField(choices=[('-', '-'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='-', max_length=50)),
                ('feedback_penolakan_penyelia', models.TextField(blank=True, null=True)),
                ('feedback_dosen', models.TextField(blank=True, null=True)),
                ('history', models.JSONField(default=dict)),
                ('file_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('Belum Dicek', 'Belum Dicek'), ('Perlu Revisi', 'Perlu Revisi'), ('Sudah Bisa Diberikan ke Perpustakaan', 'Sudah Bisa Diberikan ke Perpustakaan')], default='Belum Dicek', max_length=50)),
                ('sks_klaim', models.IntegerField()),
                ('status_persetujuan_dosen', models.CharField(choices=[('-', '-'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='-', max_length=50)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_detil.pendaftaranmbkm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
